name:                tighub
version:             0.1.0.0
github:              "githubuser/hussein-aitlahcen"
license:             GPL-3
author:              "Hussein Ait Lahcen"
maintainer:          "hussein.aitlahcen@gmail.com"
copyright:           "2018 Hussein Ait Lahccen"

dependencies:
- base >= 4.7 && < 5
- cmdargs
- bytestring
- text
- memory
- gitlib
- gitlib-libgit2
- cryptonite

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror

executables:
  tighub-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - tighub

tests:
  tighub-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - tighub
